version: "3.9"

services:

  valet:

    container_name: valet
    image: "smurfworks/valet-workspaces:1.0.0"
    tty: true
    restart: unless-stopped

    volumes:
      - "./workspaces:/home/valet/workspaces"
      - "./config/.bashrc:/home/valet/.bashrc"
      - "./secure/ssh/config:/home/valet/.ssh/config"
      - "./secure/ssh/keys:/home/valet/.ssh/keys"

    ports:
      - "3000:3000"

    dns:
      - 127.0.0.1
      - 8.8.8.8

    extra_hosts:
      - "docker-desktop:127.0.0.1"

  database:

    container_name: database
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root1234

    ports:
      - "3306:3306"

  memorycache:

    container_name: memorycache
    image: "redis:6.2.6"
    
    ports:
      - "6379:6379"
